// <auto-generated />
using DisneyMoviesApi.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DisneyMoviesApi.Migrations
{
    [DbContext(typeof(DisneyMoviesDbContext))]
    partial class DisneyMoviesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("NOCASE")
                .HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("DisneyMoviesApi.Models.DisneyMovie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Directors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("directors");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("genre");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("image");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("link");

                    b.Property<string>("Metascore")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metascore");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<string>("Runtime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("runtime");

                    b.Property<string>("Stars")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stars");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("year");

                    b.HasKey("MovieId");

                    b.ToTable("disney_movies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
